//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC毕业设计.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consume
    {
        public string Cus_id { get; set; }
        public string Cus_detail { get; set; }
        public decimal Cus_money { get; set; }
        public string Ifvip { get; set; }
        public string Cus_want { get; set; }
        public System.DateTime Cus_time { get; set; }
        public string Cus_way { get; set; }
        public Nullable<long> Card_id { get; set; }
        public int shop_id { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
