//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC毕业设计.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Staff = new HashSet<Staff>();
            this.Staff1 = new HashSet<Staff>();
        }
    
        public string Department_id { get; set; }
        public string Department_name { get; set; }
        public string Department_txt { get; set; }
    
        public virtual ICollection<Staff> Staff { get; set; }
        public virtual ICollection<Staff> Staff1 { get; set; }
    }
}
