//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC毕业设计.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        {
            this.MealFood = new HashSet<MealFood>();
            this.Record = new HashSet<Record>();
        }
    
        public int Food_id { get; set; }
        public string Food_name { get; set; }
        public decimal Food_sale { get; set; }
        public decimal Food_ka { get; set; }
        public string Food_area { get; set; }
        public string Food_txt { get; set; }
        public Nullable<int> shop_id { get; set; }
        public Nullable<int> FoodType_id { get; set; }
        public string Food_pic { get; set; }
    
        public virtual FoodType FoodType { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual ICollection<MealFood> MealFood { get; set; }
        public virtual ICollection<Record> Record { get; set; }
    }
}
