//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC毕业设计.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public long Card_id { get; set; }
        public string Card_name { get; set; }
        public System.DateTime Card_bir { get; set; }
        public Nullable<decimal> Cus_height { get; set; }
        public Nullable<decimal> Cus_weight { get; set; }
        public Nullable<decimal> BFR { get; set; }
        public decimal Card_balance { get; set; }
        public Nullable<long> Card_integral { get; set; }
        public string Card_pic { get; set; }
        public int vip_id { get; set; }
        public System.DateTime Card_begin { get; set; }
        public System.DateTime Card_end { get; set; }
        public string Card_sex { get; set; }
        public string Id_card { get; set; }
        public string Card_number { get; set; }
        public string Card_state { get; set; }
        public Nullable<int> staff_id { get; set; }
        public int shop_id { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Vip Vip { get; set; }
    }
}
