//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC毕业设计.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Staff
    {
        public Nullable<long> num { get; set; }
        public int staff_id { get; set; }
        public string staff_name { get; set; }
        public System.DateTime staff_bir { get; set; }
        public string staff_sex { get; set; }
        public string staff_city { get; set; }
        public string staff_address { get; set; }
        public string staff_idcard { get; set; }
        public string staff_number { get; set; }
        public string Department_id { get; set; }
        public int shop_id { get; set; }
        public decimal staff_score { get; set; }
        public Nullable<decimal> staff_salary { get; set; }
        public System.DateTime staff_begin { get; set; }
        public string staff_state { get; set; }
        public string staff_txt { get; set; }
        public string staff_pic { get; set; }
        public string shop_name { get; set; }
        public string department_name { get; set; }
    }
}
